[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20", "postgresql"]

[phases.install]
cmds = [
  "python3 -m pip install -r backend/requirements.txt",
  "cd frontend && NODE_OPTIONS=--max-old-space-size=2048 npm install && npm run build"
]

[start]
cmd = "cd backend && python3 main.py"
